// <auto-generated />
using System;
using FootballRanking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballRanking.Infrastructure.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20260725141649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballRanking.Core.Entities.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<short?>("FoundedYear")
                        .HasColumnType("smallint");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClubId");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Competition", b =>
                {
                    b.Property<int>("CompetitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionId"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("CompetitionId");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Performance", b =>
                {
                    b.Property<int>("PerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerformanceId"));

                    b.Property<short>("Assists")
                        .HasColumnType("smallint");

                    b.Property<short>("Clearances")
                        .HasColumnType("smallint");

                    b.Property<short>("Dribbles")
                        .HasColumnType("smallint");

                    b.Property<short>("Goals")
                        .HasColumnType("smallint");

                    b.Property<short>("Interceptions")
                        .HasColumnType("smallint");

                    b.Property<short>("Matches")
                        .HasColumnType("smallint");

                    b.Property<short>("MinutesPlayed")
                        .HasColumnType("smallint");

                    b.Property<decimal>("PassAccuracy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Passes")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("RedCards")
                        .HasColumnType("tinyint");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Shots")
                        .HasColumnType("smallint");

                    b.Property<short>("ShotsOnTarget")
                        .HasColumnType("smallint");

                    b.Property<short>("SuccessfulDribbles")
                        .HasColumnType("smallint");

                    b.Property<short>("Tackles")
                        .HasColumnType("smallint");

                    b.Property<byte>("YellowCards")
                        .HasColumnType("tinyint");

                    b.HasKey("PerformanceId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Height")
                        .HasColumnType("smallint");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("PreferredFoot")
                        .HasColumnType("int");

                    b.Property<byte?>("ShirtNumber")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Weight")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerId");

                    b.HasIndex("ClubId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Stadium", b =>
                {
                    b.Property<int>("StadiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StadiumId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StadiumId");

                    b.HasIndex("ClubId")
                        .IsUnique();

                    b.ToTable("Stadiums");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Website", b =>
                {
                    b.Property<int>("WebsiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WebsiteId"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WebsiteId");

                    b.HasIndex("ClubId");

                    b.ToTable("Websites");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Club", b =>
                {
                    b.HasOne("FootballRanking.Core.Entities.Competition", "Competition")
                        .WithMany("Clubs")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Performance", b =>
                {
                    b.HasOne("FootballRanking.Core.Entities.Player", "Player")
                        .WithMany("Performances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Player", b =>
                {
                    b.HasOne("FootballRanking.Core.Entities.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Stadium", b =>
                {
                    b.HasOne("FootballRanking.Core.Entities.Club", "Club")
                        .WithOne("Stadium")
                        .HasForeignKey("FootballRanking.Core.Entities.Stadium", "ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Website", b =>
                {
                    b.HasOne("FootballRanking.Core.Entities.Club", "Club")
                        .WithMany("Websites")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Club", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Stadium");

                    b.Navigation("Websites");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Competition", b =>
                {
                    b.Navigation("Clubs");
                });

            modelBuilder.Entity("FootballRanking.Core.Entities.Player", b =>
                {
                    b.Navigation("Performances");
                });
#pragma warning restore 612, 618
        }
    }
}
